import type { Metadata } from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
	title: 'ImobJS',
	description: 'Generated by ImobJS',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pt-BR'>
			<body className=''>{children}</body>
		</html>
	)
}
