import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import logotipo from '@/images/logotipo.svg'
import imobjs from '@/images/imobjs_logo.svg'

export const metadata: Metadata = {
	title: 'ImobJS',
	description: 'Generated by ImobJS',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<main className='bg-[#282a36] text-[#f8f8f2] min-h-dvh px-8'>
			<div className='flex gap-4'>
				<Link href='/painel'>painel</Link>
				<Link href='/painel/empreendimentos'>empreendimentos</Link>
				<Link href='/'>sair</Link>
			</div>
			<section className='h-full'>
				<div className='container mx-auto'>{children}</div>
			</section>
		</main>
	)
}
