import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import logotipo from '@/images/logotipo.svg'
import imobjs from '@/images/imobjs_logo.svg'
import Footer from '@/components/Footer'
import Header from '@/components/Header'

export const metadata: Metadata = {
	title: 'ImobJS',
	description: 'Generated by ImobJS',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<main className='bg-gray-950 text-gray-50 min-h-dvh'>
			<Header />
			<section className='h-full'>
				<div className='container mx-auto'>{children}</div>
			</section>
			<Footer />
		</main>
	)
}
