import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import Header from '@/components/Header'

export const metadata: Metadata = {
	title: 'ImobJS',
	description: 'Generated by ImobJS',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<main className='bg-gray-950 text-gray-50 min-h-dvh'>
			<Header />
			<section className='h-full'>
				<div className='container mx-auto'>{children}</div>
			</section>
			<Footer />
		</main>
	)
}
